services:
  postgres:
    image: postgres:latest
    container_name: postgres_db_library
    restart: unless-stopped
    environment:
      POSTGRES_USER: library
      POSTGRES_PASSWORD: library
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
